### job-hunting Configuration
###
### THIS FILE IS GENERATED. CHANGES/CONTRIBUTIONS IN THE REPO WILL BE
### OVERWRITTEN!
###
### You should rename this file before configuring your server. Changes to
### documentation and defaults can be contributed in source code at
### src/config/mod.rs. This file is generated when building.
###
### Any values pre-populated are the default values for said config option.
###
### At the minimum, you MUST edit all the config options to your environment
### that say "YOU NEED TO EDIT THIS".
###

[global]

# This item is undocumented. Please contribute documentation for it.
#
#server_name = localhost.localdomain

# The default address (IPv4 or IPv6) continuwuity will listen on.
#
# If you are using Docker or a container NAT networking setup, this must
# be "0.0.0.0".
#
#
#address = 127.0.0.1

# The port(s) continuwuity will listen on.
#
# For reverse proxying, see:
# https://continuwuity.org/deploying/generic.html#setting-up-the-reverse-proxy
#
# If you are using Docker, don't change this, you'll need to map an
# external port to this.
#
#port = 3000

# The database connection URL.
#
#database_url = sqlite://db.sqlite?mode=rwc

# Secret key for signing access tokens.
#
#auth_access_token_secret = "QLjJTeVblAlM47de"

# Access token expiration time in seconds.
#
#auth_access_token_expires_in = 28800

# Secret key for signing refresh tokens.
#
#auth_refresh_token_secret = "N8lI0uitNzJl6vYK"

# Refresh token expiration time in seconds.
#
#auth_refresh_token_expires_in = 15897600

# JWT audience claim.
#
#auth_audience = "audience"

# JWT issuer claim.
#
#auth_issuer = "issuer"

# OAuth client ID.
#
#auth_client_id = "d1aicsr57dijo7h963ig"

# OAuth client secret.
#
#auth_client_secret = "ujTgh2lEQYy0PXhK"

# Maximum size of history file in bytes.
#
#history_file_max_size = 5368709120
