networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: "postgres:18.4"
    environment:
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    networks:
      - app-tier

