//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use crate::schema::date_time_with_time_zone_or_null_schema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "company")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub platform: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub start_date: Option<chrono::NaiveDate>,
    pub status: Option<String>,
    pub legal_person: Option<String>,
    pub unified_code: Option<String>,
    pub website: Option<String>,
    pub insurance_num: Option<i32>,
    pub self_risk: Option<i32>,
    pub union_risk: Option<i32>,
    pub address: Option<String>,
    pub scope: Option<String>,
    pub tax_no: Option<String>,
    pub industry: Option<String>,
    pub license_number: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub longitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub latitude: Option<f64>,
    #[sea_orm(column_type = "Float", nullable)]
    pub reg_capital_value: Option<f64>,
    pub reg_capital_currency: Option<String>,
    pub source_url: Option<String>,
    pub source_record_id: Option<String>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub source_refresh_datetime: Option<DateTimeWithTimeZone>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub create_datetime: Option<DateTimeWithTimeZone>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub update_datetime: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
