//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod company;
pub mod company_tag;
pub mod config;
pub mod job;
pub mod job_tag;
pub mod schema;
pub mod tag;
pub mod user;
