//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::config::Entity as Config;
pub use super::job::Entity as Job;
pub use super::job_tag::Entity as JobTag;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
