//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use crate::schema::date_time_with_time_zone_or_null_schema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub plan_id: Option<String>,
    pub r#type: Option<Type>,
    pub data_id: Option<String>,
    pub status: Option<Status>,
    pub error_reason: Option<String>,
    pub cost_time: Option<i32>,
    pub retry_count: Option<i32>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub create_datetime: Option<DateTimeWithTimeZone>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub update_datetime: Option<DateTimeWithTimeZone>,
}

#[derive(EnumIter, DeriveActiveEnum, Debug, ToSchema, PartialEq, Clone, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum Type {
    #[sea_orm(string_value = "JOB_DATA_DOWNLOAD")]
    JobDataDownload,
    #[sea_orm(string_value = "JOB_DATA_MERGE")]
    JobDataMerge,
    #[sea_orm(string_value = "COMPANY_DATA_DOWNLOAD")]
    CompanyDataDownload,
    #[sea_orm(string_value = "COMPANY_DATA_MERGE")]
    CompanyDataMerge,
}

impl Type {
    pub fn is_download(&self) -> bool {
        matches!(self, Type::JobDataDownload | Type::CompanyDataDownload)
    }

    pub fn is_merge(&self) -> bool {
        matches!(self, Type::JobDataMerge | Type::CompanyDataMerge)
    }
}

#[derive(EnumIter, DeriveActiveEnum, Debug, ToSchema, PartialEq, Clone, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum Status {
    #[sea_orm(string_value = "READY")]
    Ready,
    #[sea_orm(string_value = "RUNNING")]
    Running,
    #[sea_orm(string_value = "CANCEL")]
    Cancel,
    #[sea_orm(string_value = "FINISHED")]
    Finished,
    #[sea_orm(string_value = "FINISHED_BUT_ERROR")]
    FinishedButError,
    #[sea_orm(string_value = "ERROR")]
    Error,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
