//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use crate::schema::date_time_with_time_zone_or_null_schema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "task_data_download")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: Option<Type>,
    pub user_name: Option<String>,
    pub repo_name: Option<String>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub datetime: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Json", nullable)]
    pub config: Option<String>,
    pub data_id: Option<String>,
    pub seq: Option<i32>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub create_datetime: Option<DateTimeWithTimeZone>,
    #[schema(schema_with = date_time_with_time_zone_or_null_schema)]
    pub update_datetime: Option<DateTimeWithTimeZone>,
}

#[derive(EnumIter, DeriveActiveEnum, Debug, ToSchema, PartialEq, Clone, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum Type {
    #[sea_orm(string_value = "JOB_DATA_DOWNLOAD")]
    JobDataDownload,
    #[sea_orm(string_value = "COMPANY_DATA_DOWNLOAD")]
    CompanyDataDownload,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
