inheritedBy:
  toolchains: ['javascript', 'typescript']

tasks:
  ensure-deps:
    command: 'pnpm install'
    inputs:
      - '/pnpm-lock.yaml'
      - '/pnpm-workspace.yaml'
      - 'package.json'
    outputs:
      - '/node_modules'
    options:
      cache: true
      mutex: 'pnpm-install'
