[package]
name = "api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["async-await"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "chrono"] }
figment = { workspace = true, features = ["toml", "env"] }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
sea-orm = { workspace = true, features = [
  "with-chrono",
  "debug-print",
  "sqlx-postgres",
  "sqlx-sqlite",
  "with-rust_decimal",
  "runtime-tokio-rustls",
  "macros",
] }
thiserror = { workspace = true }
tower-http = { workspace = true, features = [
  "trace",
  "timeout",
  "limit",
  "cors",
  "normalize-path",
  "auth",
  "compression-full",
] }
xid = { workspace = true }
bytesize = { workspace = true }
validator = { workspace = true, features = ["derive"] }
axum-valid = { workspace = true, features = ["full_validator"] }
regex = { workspace = true }
idgenerator = { workspace = true }
bcrypt = { workspace = true }
jsonwebtoken = { workspace = true, features = ["rust_crypto"] }
utoipa = { workspace = true, features = ["axum_extras", "debug", "chrono"] }
utoipa-axum = { workspace = true, features = ["debug"] }
utoipa-scalar = { workspace = true, features = ["axum"] }
serde_json = { workspace = true }
http-body-util = { workspace = true }
mime = { workspace = true }
chrono = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres", "gitea"] }
base64 = { workspace = true }
entity = { path = "../entity" }
migration = { path = "../migration" }
service = { path = "../service" }
framework = { path = "../framework" }
web = { path = "../web" }
framework-macros = { path = "../framework/macros" }
strum = { workspace = true }
strum_macros = { workspace = true }
macros = { path = "../macros" }
either = { workspace = true, features = ["serde"] }
tokio-util = { workspace = true }
futures = { workspace = true }
tower-layer = { workspace = true }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
cucumber = { workspace = true, features = ["tracing", "output-json"] }
futures = { workspace = true }
