/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutAdminRouteRouteImport } from './routes/_pathlessLayout.admin/route'
import { Route as PathlessLayoutAdminIndexRouteImport } from './routes/_pathlessLayout.admin/index'
import { Route as PathlessLayoutAdminSyncRouteImport } from './routes/_pathlessLayout.admin/sync'
import { Route as PathlessLayoutAdminJobsRouteImport } from './routes/_pathlessLayout.admin/jobs'
import { Route as PathlessLayoutAdminCompaniesRouteImport } from './routes/_pathlessLayout.admin/companies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/_pathlessLayout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutAdminRouteRoute =
  PathlessLayoutAdminRouteRouteImport.update({
    id: '/_pathlessLayout/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const PathlessLayoutAdminIndexRoute =
  PathlessLayoutAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)
const PathlessLayoutAdminSyncRoute = PathlessLayoutAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => PathlessLayoutAdminRouteRoute,
} as any)
const PathlessLayoutAdminJobsRoute = PathlessLayoutAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => PathlessLayoutAdminRouteRoute,
} as any)
const PathlessLayoutAdminCompaniesRoute =
  PathlessLayoutAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/': typeof PathlessLayoutIndexRoute
  '/admin/companies': typeof PathlessLayoutAdminCompaniesRoute
  '/admin/jobs': typeof PathlessLayoutAdminJobsRoute
  '/admin/sync': typeof PathlessLayoutAdminSyncRoute
  '/admin/': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof PathlessLayoutIndexRoute
  '/admin/companies': typeof PathlessLayoutAdminCompaniesRoute
  '/admin/jobs': typeof PathlessLayoutAdminJobsRoute
  '/admin/sync': typeof PathlessLayoutAdminSyncRoute
  '/admin': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/_pathlessLayout/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/admin/companies': typeof PathlessLayoutAdminCompaniesRoute
  '/_pathlessLayout/admin/jobs': typeof PathlessLayoutAdminJobsRoute
  '/_pathlessLayout/admin/sync': typeof PathlessLayoutAdminSyncRoute
  '/_pathlessLayout/admin/': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin'
    | '/'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/sync'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/sync'
    | '/admin'
  id:
    | '__root__'
    | '/login'
    | '/_pathlessLayout/admin'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/admin/companies'
    | '/_pathlessLayout/admin/jobs'
    | '/_pathlessLayout/admin/sync'
    | '/_pathlessLayout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  PathlessLayoutAdminRouteRoute: typeof PathlessLayoutAdminRouteRouteWithChildren
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/admin': {
      id: '/_pathlessLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PathlessLayoutAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/admin/': {
      id: '/_pathlessLayout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PathlessLayoutAdminIndexRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/sync': {
      id: '/_pathlessLayout/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof PathlessLayoutAdminSyncRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/jobs': {
      id: '/_pathlessLayout/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof PathlessLayoutAdminJobsRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
    '/_pathlessLayout/admin/companies': {
      id: '/_pathlessLayout/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof PathlessLayoutAdminCompaniesRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
  }
}

interface PathlessLayoutAdminRouteRouteChildren {
  PathlessLayoutAdminCompaniesRoute: typeof PathlessLayoutAdminCompaniesRoute
  PathlessLayoutAdminJobsRoute: typeof PathlessLayoutAdminJobsRoute
  PathlessLayoutAdminSyncRoute: typeof PathlessLayoutAdminSyncRoute
  PathlessLayoutAdminIndexRoute: typeof PathlessLayoutAdminIndexRoute
}

const PathlessLayoutAdminRouteRouteChildren: PathlessLayoutAdminRouteRouteChildren =
  {
    PathlessLayoutAdminCompaniesRoute: PathlessLayoutAdminCompaniesRoute,
    PathlessLayoutAdminJobsRoute: PathlessLayoutAdminJobsRoute,
    PathlessLayoutAdminSyncRoute: PathlessLayoutAdminSyncRoute,
    PathlessLayoutAdminIndexRoute: PathlessLayoutAdminIndexRoute,
  }

const PathlessLayoutAdminRouteRouteWithChildren =
  PathlessLayoutAdminRouteRoute._addFileChildren(
    PathlessLayoutAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  PathlessLayoutAdminRouteRoute: PathlessLayoutAdminRouteRouteWithChildren,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
