/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutAdminRouteRouteImport } from './routes/_pathlessLayout.admin/route'
import { Route as PathlessLayoutAdminIndexRouteImport } from './routes/_pathlessLayout.admin/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/_pathlessLayout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutAdminRouteRoute =
  PathlessLayoutAdminRouteRouteImport.update({
    id: '/_pathlessLayout/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const PathlessLayoutAdminIndexRoute =
  PathlessLayoutAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PathlessLayoutAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/': typeof PathlessLayoutIndexRoute
  '/admin/': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof PathlessLayoutIndexRoute
  '/admin': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/_pathlessLayout/admin': typeof PathlessLayoutAdminRouteRouteWithChildren
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/admin/': typeof PathlessLayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/admin' | '/' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/admin'
  id:
    | '__root__'
    | '/login'
    | '/_pathlessLayout/admin'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  PathlessLayoutAdminRouteRoute: typeof PathlessLayoutAdminRouteRouteWithChildren
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/admin': {
      id: '/_pathlessLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PathlessLayoutAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/admin/': {
      id: '/_pathlessLayout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PathlessLayoutAdminIndexRouteImport
      parentRoute: typeof PathlessLayoutAdminRouteRoute
    }
  }
}

interface PathlessLayoutAdminRouteRouteChildren {
  PathlessLayoutAdminIndexRoute: typeof PathlessLayoutAdminIndexRoute
}

const PathlessLayoutAdminRouteRouteChildren: PathlessLayoutAdminRouteRouteChildren =
  {
    PathlessLayoutAdminIndexRoute: PathlessLayoutAdminIndexRoute,
  }

const PathlessLayoutAdminRouteRouteWithChildren =
  PathlessLayoutAdminRouteRoute._addFileChildren(
    PathlessLayoutAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  PathlessLayoutAdminRouteRoute: PathlessLayoutAdminRouteRouteWithChildren,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
