[package]
name = "service"
version.workspace = true
authors.workspace = true
edition.workspace = true


[dependencies]
sea-orm = { workspace = true, features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
  "debug-print",
] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
git2 = { workspace = true }
ssh-key = { workspace = true, features = ["getrandom", "ed25519"] }
chrono = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres", "gitea"] }
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
num_cpus = { workspace = true }
openssl = { workspace = true, features = ["vendored"] }
calamine = "0.26"
reqwest = { version = "0.12", features = ["json"] }
tempfile = "3"
xid = { workspace = true }
sha2 = "0.10"
hex = "0.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true }
validator = { workspace = true, features = ["derive"] }
migration = { path = "../migration" }
entity = { path = "../entity" }
framework = { path = "../framework" }

[features]
default = []
vendored-openssl = ["git2/vendored-openssl"]
