[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.10", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
  "debug-print",
] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
git2 = "0.20.1"
ssh-key = { version = "0.6.7", features = ["getrandom", "ed25519"] }
chrono = "0.4.40"
testcontainers = "0.24.0"
testcontainers-modules = { version = "0.12.1", features = [
  "postgres",
  "gitea",
] }
uuid = { version = "1.16.0", features = ["v4"] }
tokio = { version = "1.44.2", features = ["full"] }
migration = { path = "../migration" }
entity = { path = "../entity" }
