name: analysis-ci
run-name: ${{ github.actor }} analysis CI

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "libs/analysis/**"
      - ".github/**"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - dev
    paths:
      - "libs/analysis/**"
      - ".github/**"
      - "pnpm-lock.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-pnpm

      - name: Setup e2e tests
        run: |
          pnpm exec nx run analysis:e2e:install

      - name: Run e2e tests
        run: |
          pnpm exec nx run analysis:test
