name: build-extension
run-name: ${{ github.actor }} extension build
on:
  push:
    branches:
      - dev
    tags:
      - '@job-hunting/extension@*'
  pull_request:
    branches:
      - dev
env:
  ROOT_DIR: apps/extension/

permissions:
  contents: write

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Set Version Env
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=$(echo '${{  github.ref_name }}' | sed -e 's/\@job-hunting\/extension\@//g')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip extensions
        run: |
          pnpm install
          pnpm exec nx run @job-hunting/extension:zip
          pnpm exec nx run @job-hunting/extension:zip:firefox

      - name: Setup e2e tests from cache
        uses: actions/cache@v4
        id: e2e-tests-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/playwright.config.ts') }}

      - name: Setup e2e tests
        run: |
          pnpm exec nx run @job-hunting/extension:e2e:install
        if: steps.e2e-tests-cache.outputs.cache-hit != 'true'

      - name: Run e2e tests
        run: |
          pnpm exec nx run @job-hunting/extension:e2e

      - name: (cucumber-report)Upload e2e tests report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: extension-e2e-tests-cucumber-report
          path: ${{ env.ROOT_DIR }}cucumber-report/
          retention-days: 30

      - name: (allure-report)Set up JDK
        uses: actions/setup-java@v3
        if: ${{ !cancelled() }}
        with:
          distribution: zulu
          java-version: 17
      - name: (allure-report)Load test report history
        uses: actions/checkout@v3
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: (allure-report)Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: ${{ !cancelled() }}
        with:
          gh_pages: gh-pages
          allure_history: gh-pages
          allure_results: ${{ env.ROOT_DIR }}allure-results
      - name: (allure-report)Upload e2e tests report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: extension-e2e-tests-allure-report
          path: allure-report/
          retention-days: 30
      - name: (allure-report)Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ !cancelled() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages

      - name: Rename dist files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          CHROME_ZIP=$(ls ${{ env.ROOT_DIR }}.output/job-huntingextension-*-chrome.zip)
          FIREFOX_ZIP=$(ls ${{ env.ROOT_DIR }}.output/job-huntingextension-*-firefox.zip)

          mv "$CHROME_ZIP" ${{ env.ROOT_DIR }}.output/job-hunting-extension-chrome-${{ env.VERSION }}.zip
          mv "$FIREFOX_ZIP" ${{ env.ROOT_DIR }}.output/job-hunting-extension-firefox-${{ env.VERSION }}.zip

      - name: Deploy chrome dist branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: dist/chrome-${{  github.ref_name }}
          folder: ${{ env.ROOT_DIR }}.output/chrome-mv3
        if: github.event_name != 'pull_request'

      - name: Deploy firefox dist branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: dist/firefox-${{  github.ref_name }}
          folder: ${{ env.ROOT_DIR }}.output/firefox-mv2
        if: github.event_name != 'pull_request'

      - name: Gen latest changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          awk '/^##[^#]/{print NR}' ${{ env.ROOT_DIR }}CHANGELOG.md | head -n 2 | xargs | tr ' ' ',' | xargs -I {} sed -n {}p  ${{ env.ROOT_DIR }}CHANGELOG.md | sed '$d' > ${{ env.ROOT_DIR }}CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ env.ROOT_DIR }}CHANGELOG.txt
          make_latest: true
          files: |
            ${{ env.ROOT_DIR }}.output/job-hunting-extension-chrome-${{ env.VERSION }}.zip
            ${{ env.ROOT_DIR }}.output/job-hunting-extension-firefox-${{ env.VERSION }}.zip
