name: docs
run-name: ${{ github.actor }} docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch to run against
        default: dev
  push:
    branches:
      - dev
    paths:
      - "docs/**"
      - ".github/**"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - dev
    paths:
      - "docs/**"
      - ".github/**"
      - "pnpm-lock.yaml"

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-mdbook

      - name: Run tests
        run: |
          cd docs
          mdbook test

  deploy:
    if: github.event_name != 'pull_request'
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-mdbook

      - name: Build docs
        run: |
          cd docs
          mdbook build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          publish_branch: gh-pages
          force_orphan: true
