name: extension-ci
run-name: ${{ github.actor }} extension CI

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "apps/extension/**"
      - "libs/**"
      - ".github/**"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - dev
    paths:
      - "apps/extension/**"
      - "libs/**"
      - ".github/**"
      - "pnpm-lock.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup-pnpm

      - name: Run unit tests
        run: |
          pnpm exec nx run @job-hunting/extension:test:unit

      - name: Setup e2e tests
        run: |
          pnpm exec nx run @job-hunting/extension:test:e2e:install

      - name: Run e2e tests
        id: e2e
        run: |
          pnpm exec nx run @job-hunting/extension:test:e2e

      - name: (allure-report) Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        if: steps.e2e.outcome == 'success' && !cancelled()
        with:
          distribution: zulu
          java-version: 17

      - name: (allure-report) Load test report history
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        if: steps.e2e.outcome == 'success' && !cancelled()
        continue-on-error: true
        with:
          ref: gh-test
          path: gh-test
          fetch-depth: 1

      - name: (allure-report) Build test report
        uses: simple-elf/allure-report-action@53ebb757a2097edc77c53ecef4d454fc2f2f774c
        if: steps.e2e.outcome == 'success' && !cancelled()
        with:
          gh_pages: gh-test
          allure_history: gh-test
          allure_results: apps/extension/allure-results

      - name: (allure-report) Upload test report to action artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        if: steps.e2e.outcome == 'success' && !cancelled()
        with:
          name: extension-e2e-tests-allure-report
          path: allure-report/
          retention-days: 30

      - name: (cucumber-report) Upload test report to action artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        if: steps.e2e.outcome == 'success' && !cancelled()
        with:
          name: extension-e2e-tests-cucumber-report
          path: apps/extension/cucumber-report/
          retention-days: 30
